graph LR
    about_us[about-us]
    about_us_conrad_j_kuyawa[about-us/conrad-j-kuyawa]
    contact[contact]
    criminal_defense[criminal-defense]
    criminal_defense_domestic_violence[criminal-defense/domestic-violence]
    criminal_defense_drug_crimes[criminal-defense/drug-crimes]
    criminal_defense_dui[criminal-defense/dui]
    criminal_defense_theft_crimes[criminal-defense/theft-crimes]
    index_html[index.html]
    landlord[landlord]
    landlord_evictions[landlord/evictions]
    landlord_landlord_representation[landlord/landlord-representation]
    landlord_lease_rental_agreements[landlord/lease-rental-agreements]
    landlord_tenant_representation[landlord/tenant-representation]
    personal_injury[personal-injury]
    personal_injury_bus_accidents[personal-injury/bus-accidents]
    personal_injury_car_accidents[personal-injury/car-accidents]
    personal_injury_hospital_negligence[personal-injury/hospital-negligence]
    personal_injury_motorcycle_accidents[personal-injury/motorcycle-accidents]
    personal_injury_nursing_home_abuse_neglect[personal-injury/nursing-home-abuse-neglect]
    personal_injury_premises_liability[personal-injury/premises-liability]
    personal_injury_slip_and_fall[personal-injury/slip-and-fall]
    personal_injury_truck_accidents[personal-injury/truck-accidents]
    personal_injury_wrongful_death[personal-injury/wrongful-death]
    results[results]
    testimonials[testimonials]
    about_us --> contact
    about_us --> personal_injury
    about_us --> personal_injury_car_accidents
    about_us --> testimonials
    about_us_conrad_j_kuyawa --> index_html
    criminal_defense --> about_us
    criminal_defense --> contact
    criminal_defense --> criminal_defense_domestic_violence
    criminal_defense --> criminal_defense_drug_crimes
    criminal_defense --> criminal_defense_dui
    criminal_defense --> criminal_defense_theft_crimes
    criminal_defense --> testimonials
    criminal_defense_domestic_violence --> about_us
    criminal_defense_domestic_violence --> about_us_conrad_j_kuyawa
    criminal_defense_domestic_violence --> contact
    criminal_defense_domestic_violence --> testimonials
    criminal_defense_drug_crimes --> contact
    criminal_defense_drug_crimes --> testimonials
    criminal_defense_dui --> about_us
    criminal_defense_dui --> contact
    criminal_defense_dui --> results
    criminal_defense_dui --> testimonials
    criminal_defense_theft_crimes --> about_us
    criminal_defense_theft_crimes --> contact
    criminal_defense_theft_crimes --> testimonials
    index_html --> about_us
    index_html --> about_us_conrad_j_kuyawa
    index_html --> contact
    index_html --> criminal_defense
    index_html --> landlord
    index_html --> personal_injury
    index_html --> personal_injury_car_accidents
    index_html --> personal_injury_slip_and_fall
    index_html --> testimonials
    landlord --> about_us
    landlord --> contact
    landlord --> landlord_evictions
    landlord --> landlord_landlord_representation
    landlord --> landlord_tenant_representation
    landlord --> testimonials
    landlord_evictions --> about_us_conrad_j_kuyawa
    landlord_evictions --> contact
    landlord_evictions --> index_html
    landlord_evictions --> landlord_landlord_representation
    landlord_evictions --> landlord_lease_rental_agreements
    landlord_evictions --> landlord_tenant_representation
    landlord_evictions --> testimonials
    landlord_landlord_representation --> about_us
    landlord_landlord_representation --> about_us_conrad_j_kuyawa
    landlord_landlord_representation --> contact
    landlord_landlord_representation --> landlord_evictions
    landlord_landlord_representation --> landlord_lease_rental_agreements
    landlord_landlord_representation --> landlord_tenant_representation
    landlord_landlord_representation --> testimonials
    landlord_lease_rental_agreements --> about_us
    landlord_lease_rental_agreements --> contact
    landlord_lease_rental_agreements --> landlord_evictions
    landlord_lease_rental_agreements --> landlord_landlord_representation
    landlord_lease_rental_agreements --> landlord_tenant_representation
    landlord_lease_rental_agreements --> testimonials
    landlord_tenant_representation --> about_us_conrad_j_kuyawa
    landlord_tenant_representation --> contact
    landlord_tenant_representation --> landlord_evictions
    landlord_tenant_representation --> landlord_landlord_representation
    landlord_tenant_representation --> landlord_lease_rental_agreements
    landlord_tenant_representation --> testimonials
    personal_injury --> about_us
    personal_injury --> about_us_conrad_j_kuyawa
    personal_injury --> contact
    personal_injury --> personal_injury_bus_accidents
    personal_injury --> personal_injury_car_accidents
    personal_injury --> personal_injury_hospital_negligence
    personal_injury --> personal_injury_motorcycle_accidents
    personal_injury --> personal_injury_nursing_home_abuse_neglect
    personal_injury --> personal_injury_premises_liability
    personal_injury --> personal_injury_slip_and_fall
    personal_injury --> personal_injury_truck_accidents
    personal_injury --> personal_injury_wrongful_death
    personal_injury --> testimonials
    personal_injury_bus_accidents --> about_us
    personal_injury_bus_accidents --> personal_injury_car_accidents
    personal_injury_bus_accidents --> personal_injury_hospital_negligence
    personal_injury_bus_accidents --> personal_injury_motorcycle_accidents
    personal_injury_bus_accidents --> personal_injury_nursing_home_abuse_neglect
    personal_injury_bus_accidents --> personal_injury_premises_liability
    personal_injury_bus_accidents --> personal_injury_slip_and_fall
    personal_injury_bus_accidents --> personal_injury_truck_accidents
    personal_injury_bus_accidents --> personal_injury_wrongful_death
    personal_injury_bus_accidents --> testimonials
    personal_injury_car_accidents --> about_us_conrad_j_kuyawa
    personal_injury_car_accidents --> contact
    personal_injury_car_accidents --> personal_injury_bus_accidents
    personal_injury_car_accidents --> personal_injury_hospital_negligence
    personal_injury_car_accidents --> personal_injury_motorcycle_accidents
    personal_injury_car_accidents --> personal_injury_nursing_home_abuse_neglect
    personal_injury_car_accidents --> personal_injury_premises_liability
    personal_injury_car_accidents --> personal_injury_slip_and_fall
    personal_injury_car_accidents --> personal_injury_truck_accidents
    personal_injury_car_accidents --> personal_injury_wrongful_death
    personal_injury_car_accidents --> testimonials
    personal_injury_hospital_negligence --> about_us
    personal_injury_hospital_negligence --> personal_injury_bus_accidents
    personal_injury_hospital_negligence --> personal_injury_car_accidents
    personal_injury_hospital_negligence --> personal_injury_motorcycle_accidents
    personal_injury_hospital_negligence --> personal_injury_nursing_home_abuse_neglect
    personal_injury_hospital_negligence --> personal_injury_premises_liability
    personal_injury_hospital_negligence --> personal_injury_slip_and_fall
    personal_injury_hospital_negligence --> personal_injury_truck_accidents
    personal_injury_hospital_negligence --> personal_injury_wrongful_death
    personal_injury_hospital_negligence --> testimonials
    personal_injury_motorcycle_accidents --> about_us
    personal_injury_motorcycle_accidents --> about_us_conrad_j_kuyawa
    personal_injury_motorcycle_accidents --> contact
    personal_injury_motorcycle_accidents --> personal_injury_bus_accidents
    personal_injury_motorcycle_accidents --> personal_injury_car_accidents
    personal_injury_motorcycle_accidents --> personal_injury_hospital_negligence
    personal_injury_motorcycle_accidents --> personal_injury_nursing_home_abuse_neglect
    personal_injury_motorcycle_accidents --> personal_injury_premises_liability
    personal_injury_motorcycle_accidents --> personal_injury_slip_and_fall
    personal_injury_motorcycle_accidents --> personal_injury_truck_accidents
    personal_injury_motorcycle_accidents --> personal_injury_wrongful_death
    personal_injury_motorcycle_accidents --> testimonials
    personal_injury_nursing_home_abuse_neglect --> about_us
    personal_injury_nursing_home_abuse_neglect --> personal_injury_bus_accidents
    personal_injury_nursing_home_abuse_neglect --> personal_injury_car_accidents
    personal_injury_nursing_home_abuse_neglect --> personal_injury_hospital_negligence
    personal_injury_nursing_home_abuse_neglect --> personal_injury_motorcycle_accidents
    personal_injury_nursing_home_abuse_neglect --> personal_injury_premises_liability
    personal_injury_nursing_home_abuse_neglect --> personal_injury_slip_and_fall
    personal_injury_nursing_home_abuse_neglect --> personal_injury_truck_accidents
    personal_injury_nursing_home_abuse_neglect --> personal_injury_wrongful_death
    personal_injury_nursing_home_abuse_neglect --> testimonials
    personal_injury_premises_liability --> about_us
    personal_injury_premises_liability --> about_us_conrad_j_kuyawa
    personal_injury_premises_liability --> contact
    personal_injury_premises_liability --> personal_injury_bus_accidents
    personal_injury_premises_liability --> personal_injury_car_accidents
    personal_injury_premises_liability --> personal_injury_hospital_negligence
    personal_injury_premises_liability --> personal_injury_motorcycle_accidents
    personal_injury_premises_liability --> personal_injury_nursing_home_abuse_neglect
    personal_injury_premises_liability --> personal_injury_slip_and_fall
    personal_injury_premises_liability --> personal_injury_truck_accidents
    personal_injury_premises_liability --> personal_injury_wrongful_death
    personal_injury_premises_liability --> testimonials
    personal_injury_slip_and_fall --> about_us
    personal_injury_slip_and_fall --> personal_injury_bus_accidents
    personal_injury_slip_and_fall --> personal_injury_car_accidents
    personal_injury_slip_and_fall --> personal_injury_hospital_negligence
    personal_injury_slip_and_fall --> personal_injury_motorcycle_accidents
    personal_injury_slip_and_fall --> personal_injury_nursing_home_abuse_neglect
    personal_injury_slip_and_fall --> personal_injury_premises_liability
    personal_injury_slip_and_fall --> personal_injury_truck_accidents
    personal_injury_slip_and_fall --> personal_injury_wrongful_death
    personal_injury_slip_and_fall --> testimonials
    personal_injury_truck_accidents --> about_us
    personal_injury_truck_accidents --> personal_injury_bus_accidents
    personal_injury_truck_accidents --> personal_injury_car_accidents
    personal_injury_truck_accidents --> personal_injury_hospital_negligence
    personal_injury_truck_accidents --> personal_injury_motorcycle_accidents
    personal_injury_truck_accidents --> personal_injury_nursing_home_abuse_neglect
    personal_injury_truck_accidents --> personal_injury_premises_liability
    personal_injury_truck_accidents --> personal_injury_slip_and_fall
    personal_injury_truck_accidents --> personal_injury_wrongful_death
    personal_injury_truck_accidents --> testimonials
    personal_injury_wrongful_death --> about_us
    personal_injury_wrongful_death --> contact
    personal_injury_wrongful_death --> personal_injury_bus_accidents
    personal_injury_wrongful_death --> personal_injury_car_accidents
    personal_injury_wrongful_death --> personal_injury_hospital_negligence
    personal_injury_wrongful_death --> personal_injury_motorcycle_accidents
    personal_injury_wrongful_death --> personal_injury_nursing_home_abuse_neglect
    personal_injury_wrongful_death --> personal_injury_premises_liability
    personal_injury_wrongful_death --> personal_injury_slip_and_fall
    personal_injury_wrongful_death --> personal_injury_truck_accidents
    personal_injury_wrongful_death --> testimonials
    testimonials --> contact
